- app/models/user.rb
allow base domain + one level of subdomains
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1090
> use dynamic hosts from app urls

- app/serializers/invitation_serializer.rb
- config/routes/v1.rb
use new version prefixed route name in serializer
> re-added missing route

- config/initializers/sentry.rb
truncate data for large request bodies
> Sentry Transaction fixes

- app/controllers/api/v1/devise/omniauth_callbacks_controller.rb
> switch of otp requirement when using oauth

- app/models/actors/app.rb
- app/models/user.rb
- db/seeds.rb
wouldn't work on empty databases otherwise
> move cleanup run after ensuring an admin user exists

- app/models/content.rb
- config/apps/identity-management/tenants/system.yml
- db/seeds.rb
use tenant from app/tenants/*.yml
> seeding rework

- db/seeds.rb
ensure_defaults needs to run after app seed
> seed fixes

- app/models/concerns/doorkeeper/access_token.rb
- config/application.rb
- db/migrate/20231012124221_redo_indexes.rb
> add ttl index to oauth tokens

- app/controllers/api/v1/access_control/apps/tenant/users_controller.rb
- config/routes/v1.rb
as the endpoint requires app specific tenant candos it must be below /apps for the correct cando determination
> fix wrong endpoint

- .rubocop.yml
- app/controllers/api/v1/user/leave_tenant_controller.rb
- config/locales/en.yml
- config/routes/v1.rb
- drops all access to the tenant
- and silence rubocop with opinions
#1247
> endpoint to have the current user leave a tenant

- app/models/functionality.rb
- app/models/role.rb
- db/seeds.rb
allow re-seeding regardless of locales selected
> add all supported languages on app create

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/user/leave_tenant_controller.rb
- added colored log formatter for non production environments
> fix for leave endpoint

- app/controllers/api/v1/user/tenants_controller.rb
- app/models/actor.rb
- change rebuild path logic to aggregation (much faster)
- narrower scope for tenant delete
> fix pathes on soft deleted actors

- Gemfile
- Gemfile.lock
contains fix for https://www.cve.org/CVERecord?id=CVE-2024-21632
> updated gems

- app/controllers/api/v1/devise/omniauth_callbacks_controller.rb
new rails needs option on redirect `, allow_other_host: true`
> fix social login

- app/controllers/api/v1/devise/omniauth_callbacks_controller.rb
- app/controllers/concerns/base_controller_methods.rb
- app/models/custom_auth_provider.rb
- app/serializers/app_info_serializer.rb
- config/locales/en.yml
- config/routes/v1_devise.rb
> 1431 custom oauth providers

- app/models/actor.rb
- app/models/actors/app.rb
- fallback for footer html is there anyhow, so no validation needed
- fix leading space in role name preventing proper seeding
> remove validation / fix role import

- app/models/actor.rb
- lib/tasks/app.rake
fixed app register via rake task
> fix for app registering

- .rubocop.yml
- Gemfile
- Gemfile.lock
https://github.com/Samedis-care/identity-management-backend/security/dependabot/8
> fix dependencies of the otp gem

- app/controllers/api/v1/app/doorkeeper/tokens_controller.rb
- app/controllers/api/v1/app/recoveries_controller.rb
- app/controllers/api/v1/devise/confirmations_controller.rb
- app/controllers/api/v1/devise/omniauth_callbacks_controller.rb
- app/mailers/application_mailer.rb
- app/mailers/devise_mailer.rb
- app/models/concerns/confirmable/recovery_email.rb
- app/models/user.rb
- app/serializers/app_user_serializer.rb
- app/views/devise_mailer/recovery_confirmation_instructions.html.erb
- app/views/devise_mailer/recovery_instructions.html.erb
- config/initializers/doorkeeper.rb
- config/locales/en.yml
- config/per_app_settings.yml
- config/routes/v1_devise.rb
backend done for https://github.com/Samedis-care/samedis-care-issues/issues/1353
> 1353 recovery email support

- app/models/concerns/confirmable/recovery_email.rb
https://github.com/Samedis-care/samedis-care-issues/issues/1353#issuecomment-2071688372
> bump to 15 minutes

- app/models/concerns/confirmable/recovery_email.rb
- config/locales/en.yml
https://github.com/Samedis-care/samedis-care-issues/issues/1353
> error handling during recovery token validation

- app/models/concerns/confirmable/recovery_email.rb
prevents registering new users
> fix broken hook

- app/serializers/app_user_serializer.rb
needed so UI can visualize a pending email change
https://github.com/Samedis-care/samedis-care-issues/issues/1561
> added unconfirmed_email to serializer

- app/controllers/api/v1/app/recoveries_controller.rb
- config/locales/en.yml
currently a 500 error is being returned with a non helpful message
> render a nice error

- Gemfile
- Gemfile.lock
- swagger/v1/swagger.json
> explicitly add csv gem

- Dockerfile
- Gemfile.lock
> ruby update

- app/controllers/api/v1/app/recoveries_controller.rb
- app/controllers/api/v1/app/user_controller.rb
- app/models/concerns/confirmable/recovery_email.rb
- pass on app name so branding is correct
- always recreate recovery token
https://github.com/Samedis-care/samedis-care-issues/issues/1642
> fixes for recovery

- app/controllers/api/v1/devise/confirmations_controller.rb
- app/mailers/devise_mailer.rb
- app/views/devise_mailer/confirmation_email_change.html.erb
- config/locales/en.yml
https://github.com/Samedis-care/samedis-care-issues/issues/1642
> fixes and new email text

- config/routes/v1.rb
to allow for comma separated multiple invite ids
https://github.com/Samedis-care/samedis-care-issues/issues/1689
> drop constraint

- app/controllers/api/v1/access_control/tenant/users_controller.rb
to support removing user from tenant
> cando to process login_allowed false

- app/controllers/concerns/base_controller_methods.rb
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1685
> missing smtp syntax error handler

- app/models/invite.rb
- app/models/user.rb
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1670
> allow mixing of switches for adding setting access groups on invites

- app/controllers/concerns/json_api.rb
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1686
> log errors without sentry

- app/views/layouts/mailer.html.erb
- config/application.rb
- config/routes.rb
- spec/mailers/previews/devise_mailer_preview.rb
- allow gradients
- mailer preview routes in non production envs
https://github.com/Samedis-care/samedis-care-issues/issues/1708
> mailer layout update

- app/views/devise_mailer/confirmation_email_change.html.erb
- app/views/devise_mailer/confirmation_instructions.html.erb
- app/views/devise_mailer/recovery_confirmation_instructions.html.erb
- app/views/devise_mailer/recovery_instructions.html.erb
- app/views/devise_mailer/reset_password_instructions.html.erb
or width will be stretched to URL at manual link part
> mailer word wrap needed

- app/views/layouts/mailer.html.erb
body with padding needs border-box
> fix sizing problem

- Gemfile
- Gemfile.lock
- config/environments/local_dev.rb
- config/environments/production.rb
with semantic logger and colorless STDOUT logging
https://github.com/Samedis-care/samedis-care-issues/issues/1735
> logger config

- app/serializers/app_user_serializer.rb
handling for exception https://sentry.samedis.care/organizations/samedis/issues/3876
> handle missing candos array

- app/controllers/api/v1/app/doorkeeper/tokens_controller.rb
duplicated to oauth standard position
> add necessary oauth params to response

- app/models/concerns/identity_management_extension.rb
needed to "..._previously_changed?" for after_save callback
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1808
> fix login history not written anymore

- app/views/layouts/mailer.html.erb
needs fallback background color or we get white text on white background
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1809
> fixed background for button

- app/models/custom_auth_provider.rb
- config/initializers/devise.rb
disable domain verification for now to get microsoft_graph 2.0.0 behaviour
> add some more sentry logging

- app/models/custom_auth_provider.rb
microsoft does not support OpenID like userinfo endpoints allows using the https://graph.microsoft.com/v1.0/me url instead
> microsoft related fixes

- app/models/user.rb
and finalize with expiring cached tenant data
https://github.com/Samedis-care/samedis-care-issues/issues/1824
> revoke tokens on soft delete

- app/serializers/app_user_serializer.rb
https://sentry.samedis.care/organizations/samedis/issues/3876
> handle no candos present

- app/controllers/api/v1/app/infos_controller.rb
resolves https://github.com/Samedis-care/samedis-care-issues/issues/1839
> require a match or 404

- app/controllers/api/v1/access_control/tenant/groups_controller.rb
- app/controllers/api/v1/access_control/tenant/profiles_controller.rb
- app/controllers/api/v1/access_control/tenant/roles_controller.rb
- app/controllers/api/v1/apps/roles_controller.rb
- app/models/actor.rb
- app/models/actors/tenant.rb
- app/models/application_document.rb
- app/serializers/group_actor_serializer.rb
- app/serializers/role_picker_serializer.rb
- config/routes/v1.rb
- allows tenant to create and manage their own profiles (group) with any combo of roles that they can assign their users to
https://github.com/Samedis-care/samedis-care-issues/issues/1847
> implemented custom profiles

- app/controllers/api/v1/apps/users_controller.rb
- app/models/actor.rb
- app/models/actors/mapping.rb
- app/models/user.rb
- db/migrate/20250206133333_change_cached_username_format.rb
- db/migrate/20250206154715_harmonize_actor_path_seperator.rb
- added friendlyname to user mappings (sortable)
- fix difference in path separator (with migration)
- performance index added
required for https://github.com/Samedis-care/samedis-care-issues/issues/1816 and future uses
> path harmonization and friendlyname

- app/models/user.rb
on changes (name) update mapping actors and their keywords
> related actors of user need to be updated

- app/models/actors/tenant.rb
skip profiles_ou create if not in defaults
> fix seed error

- Dockerfile
> docker ruby update

- app/models/actor.rb
- app/models/actors/tenant.rb
- config/initializers/hash_checksum.rb
on Actors::organization nodes in the actor tree use a checksum to decide if nodes need recursive updates or if they can be skipped.
checksum will change as soon as even just a locale below has changed
> checksum logic

- app/models/actors/tenant.rb
- app/models/invite.rb
changes invites to join standard_user group instead of employee group
> employee to standard group

- app/controllers/api/v1/app_admin_controller.rb
- app/models/actor.rb
- missing permit for support email
- skip callbacks on apps for every save
> Fix saving app records

- app/models/actor.rb
> add fullname to index

- spec/rails_helper.rb
obsoleted fixture_path method changed to fixture_paths
> fix rspec fixture_path

- .gitignore
- app/models/actor.rb
resolves https://github.com/Samedis-care/samedis-care-issues/issues/2068
> 2068 seed problem

- app/models/actors/mapping.rb
> expire cache on mapping destroy
